export interface Food {
  id: string;
  name: string;
  category: 'burgers' | 'desserts' | 'thai' | 'arab' | 'breakfast' | 'drinks';
  servingSize: number;
  servingUnit: 'g' | 'ml' | 'piece';
  calories: number;
  protein: number; // g
  carbs: number; // g
  fat: number; // g
  fiber: number; // g
  saturatedFat: number; // g
  transFat: number; // g
  cholesterol: number; // mg
  sodium: number; // mg
  potassium: number; // mg
  vitaminA: number; // mcg
  vitaminC: number; // mg
  vitaminD: number; // mcg
  vitaminE: number; // mg
  vitaminK: number; // mcg
  thiamine: number; // mg (B1)
  riboflavin: number; // mg (B2)
  niacin: number; // mg (B3)
  pantothenicAcid: number; // mg (B5)
  vitaminB6: number; // mg
  biotin: number; // mcg (B7)
  folate: number; // mcg (B9)
  vitaminB12: number; // mcg
  calcium: number; // mg
  iron: number; // mg
  magnesium: number; // mg
  phosphorus: number; // mg
  zinc: number; // mg
  copper: number; // mg
  manganese: number; // mg
  selenium: number; // mcg
  imageUrl: string;
}

export const foodsDatabase: Food[] = [
  // BURGERS
  {
    id: 'burger-classic-beef',
    name: 'Classic Beef Burger',
    category: 'burgers',
    servingSize: 200,
    servingUnit: 'g',
    calories: 540,
    protein: 30,
    carbs: 42,
    fat: 25,
    fiber: 2,
    saturatedFat: 10,
    transFat: 1,
    cholesterol: 85,
    sodium: 950,
    potassium: 420,
    vitaminA: 15,
    vitaminC: 2,
    vitaminD: 0.5,
    vitaminE: 1.2,
    vitaminK: 5,
    thiamine: 0.35,
    riboflavin: 0.35,
    niacin: 8.5,
    pantothenicAcid: 1.1,
    vitaminB6: 0.6,
    biotin: 15,
    folate: 50,
    vitaminB12: 2.4,
    calcium: 250,
    iron: 3.5,
    magnesium: 45,
    phosphorus: 320,
    zinc: 6.2,
    copper: 0.15,
    manganese: 0.35,
    selenium: 25,
    imageUrl: '/images/burger-beef.jpg',
  },
  {
    id: 'burger-cheese',
    name: 'Cheeseburger Deluxe',
    category: 'burgers',
    servingSize: 230,
    servingUnit: 'g',
    calories: 620,
    protein: 32,
    carbs: 44,
    fat: 32,
    fiber: 2,
    saturatedFat: 16,
    transFat: 1.2,
    cholesterol: 110,
    sodium: 1100,
    potassium: 450,
    vitaminA: 280,
    vitaminC: 3,
    vitaminD: 0.8,
    vitaminE: 1.5,
    vitaminK: 6,
    thiamine: 0.38,
    riboflavin: 0.45,
    niacin: 9,
    pantothenicAcid: 1.2,
    vitaminB6: 0.65,
    biotin: 18,
    folate: 55,
    vitaminB12: 2.8,
    calcium: 420,
    iron: 3.8,
    magnesium: 50,
    phosphorus: 380,
    zinc: 7,
    copper: 0.18,
    manganese: 0.4,
    selenium: 28,
    imageUrl: '/images/burger-cheese.jpg',
  },
  {
    id: 'burger-chicken',
    name: 'Chicken Burger',
    category: 'burgers',
    servingSize: 180,
    servingUnit: 'g',
    calories: 420,
    protein: 28,
    carbs: 38,
    fat: 16,
    fiber: 1.5,
    saturatedFat: 4,
    transFat: 0.5,
    cholesterol: 65,
    sodium: 780,
    potassium: 380,
    vitaminA: 12,
    vitaminC: 1,
    vitaminD: 0.3,
    vitaminE: 0.8,
    vitaminK: 3,
    thiamine: 0.25,
    riboflavin: 0.2,
    niacin: 12,
    pantothenicAcid: 0.8,
    vitaminB6: 0.8,
    biotin: 12,
    folate: 35,
    vitaminB12: 0.3,
    calcium: 180,
    iron: 2.2,
    magnesium: 35,
    phosphorus: 280,
    zinc: 2.8,
    copper: 0.1,
    manganese: 0.25,
    selenium: 18,
    imageUrl: '/images/burger-chicken.jpg',
  },

  // DESSERTS
  {
    id: 'cake-chocolate',
    name: 'Chocolate Cake',
    category: 'desserts',
    servingSize: 100,
    servingUnit: 'g',
    calories: 320,
    protein: 4,
    carbs: 48,
    fat: 14,
    fiber: 1.5,
    saturatedFat: 8,
    transFat: 0.2,
    cholesterol: 55,
    sodium: 320,
    potassium: 120,
    vitaminA: 45,
    vitaminC: 0.5,
    vitaminD: 0.2,
    vitaminE: 1,
    vitaminK: 1,
    thiamine: 0.08,
    riboflavin: 0.12,
    niacin: 0.3,
    pantothenicAcid: 0.15,
    vitaminB6: 0.05,
    biotin: 5,
    folate: 12,
    vitaminB12: 0.1,
    calcium: 35,
    iron: 1.2,
    magnesium: 25,
    phosphorus: 60,
    zinc: 0.5,
    copper: 0.15,
    manganese: 0.3,
    selenium: 8,
    imageUrl: '/images/cake-chocolate.jpg',
  },
  {
    id: 'cake-carrot',
    name: 'Carrot Cake with Frosting',
    category: 'desserts',
    servingSize: 110,
    servingUnit: 'g',
    calories: 350,
    protein: 3,
    carbs: 52,
    fat: 16,
    fiber: 1.2,
    saturatedFat: 9,
    transFat: 0.3,
    cholesterol: 60,
    sodium: 380,
    potassium: 180,
    vitaminA: 850,
    vitaminC: 2,
    vitaminD: 0.3,
    vitaminE: 1.2,
    vitaminK: 2,
    thiamine: 0.1,
    riboflavin: 0.14,
    niacin: 0.4,
    pantothenicAcid: 0.2,
    vitaminB6: 0.08,
    biotin: 6,
    folate: 18,
    vitaminB12: 0.12,
    calcium: 120,
    iron: 0.8,
    magnesium: 20,
    phosphorus: 70,
    zinc: 0.4,
    copper: 0.1,
    manganese: 0.25,
    selenium: 6,
    imageUrl: '/images/cake-carrot.jpg',
  },
  {
    id: 'baklava',
    name: 'Baklava',
    category: 'desserts',
    servingSize: 50,
    servingUnit: 'g',
    calories: 250,
    protein: 4,
    carbs: 28,
    fat: 14,
    fiber: 2,
    saturatedFat: 3,
    transFat: 0.1,
    cholesterol: 0,
    sodium: 80,
    potassium: 280,
    vitaminA: 120,
    vitaminC: 1,
    vitaminD: 0,
    vitaminE: 8,
    vitaminK: 30,
    thiamine: 0.12,
    riboflavin: 0.15,
    niacin: 2,
    pantothenicAcid: 0.6,
    vitaminB6: 0.2,
    biotin: 8,
    folate: 45,
    vitaminB12: 0,
    calcium: 140,
    iron: 2,
    magnesium: 60,
    phosphorus: 120,
    zinc: 2,
    copper: 0.4,
    manganese: 1.2,
    selenium: 5,
    imageUrl: '/images/baklava.jpg',
  },

  // THAI FOOD
  {
    id: 'pad-thai',
    name: 'Pad Thai',
    category: 'thai',
    servingSize: 250,
    servingUnit: 'g',
    calories: 350,
    protein: 14,
    carbs: 45,
    fat: 12,
    fiber: 3,
    saturatedFat: 2,
    transFat: 0,
    cholesterol: 35,
    sodium: 1200,
    potassium: 320,
    vitaminA: 280,
    vitaminC: 15,
    vitaminD: 0,
    vitaminE: 2,
    vitaminK: 45,
    thiamine: 0.28,
    riboflavin: 0.15,
    niacin: 3.5,
    pantothenicAcid: 0.7,
    vitaminB6: 0.25,
    biotin: 10,
    folate: 65,
    vitaminB12: 0.1,
    calcium: 45,
    iron: 2.8,
    magnesium: 55,
    phosphorus: 180,
    zinc: 1.5,
    copper: 0.25,
    manganese: 0.6,
    selenium: 15,
    imageUrl: '/images/pad-thai.jpg',
  },
  {
    id: 'green-curry',
    name: 'Green Curry Chicken',
    category: 'thai',
    servingSize: 280,
    servingUnit: 'g',
    calories: 380,
    protein: 24,
    carbs: 15,
    fat: 24,
    fiber: 2,
    saturatedFat: 18,
    transFat: 0,
    cholesterol: 75,
    sodium: 900,
    potassium: 450,
    vitaminA: 350,
    vitaminC: 25,
    vitaminD: 0.1,
    vitaminE: 1.8,
    vitaminK: 50,
    thiamine: 0.15,
    riboflavin: 0.22,
    niacin: 7,
    pantothenicAcid: 0.9,
    vitaminB6: 0.8,
    biotin: 8,
    folate: 35,
    vitaminB12: 0.2,
    calcium: 150,
    iron: 2.5,
    magnesium: 45,
    phosphorus: 220,
    zinc: 2.2,
    copper: 0.2,
    manganese: 0.4,
    selenium: 22,
    imageUrl: '/images/curry-green.jpg',
  },
  {
    id: 'tom-yum',
    name: 'Tom Yum Soup',
    category: 'thai',
    servingSize: 300,
    servingUnit: 'ml',
    calories: 140,
    protein: 12,
    carbs: 12,
    fat: 5,
    fiber: 1.5,
    saturatedFat: 1,
    transFat: 0,
    cholesterol: 40,
    sodium: 850,
    potassium: 380,
    vitaminA: 200,
    vitaminC: 28,
    vitaminD: 0,
    vitaminE: 0.8,
    vitaminK: 25,
    thiamine: 0.12,
    riboflavin: 0.1,
    niacin: 4,
    pantothenicAcid: 0.5,
    vitaminB6: 0.4,
    biotin: 5,
    folate: 30,
    vitaminB12: 0.15,
    calcium: 40,
    iron: 1.2,
    magnesium: 35,
    phosphorus: 120,
    zinc: 1.8,
    copper: 0.15,
    manganese: 0.3,
    selenium: 18,
    imageUrl: '/images/tom-yum.jpg',
  },

  // ARAB FOOD
  {
    id: 'shawarma',
    name: 'Chicken Shawarma',
    category: 'arab',
    servingSize: 200,
    servingUnit: 'g',
    calories: 380,
    protein: 32,
    carbs: 28,
    fat: 16,
    fiber: 2,
    saturatedFat: 4,
    transFat: 0.2,
    cholesterol: 85,
    sodium: 1000,
    potassium: 450,
    vitaminA: 25,
    vitaminC: 5,
    vitaminD: 0.2,
    vitaminE: 1.5,
    vitaminK: 15,
    thiamine: 0.25,
    riboflavin: 0.35,
    niacin: 10,
    pantothenicAcid: 1,
    vitaminB6: 0.9,
    biotin: 12,
    folate: 40,
    vitaminB12: 0.4,
    calcium: 180,
    iron: 2.8,
    magnesium: 50,
    phosphorus: 280,
    zinc: 4,
    copper: 0.2,
    manganese: 0.3,
    selenium: 28,
    imageUrl: '/images/shawarma.jpg',
  },
  {
    id: 'hummus-plate',
    name: 'Hummus Plate with Pita',
    category: 'arab',
    servingSize: 200,
    servingUnit: 'g',
    calories: 320,
    protein: 12,
    carbs: 32,
    fat: 15,
    fiber: 8,
    saturatedFat: 2,
    transFat: 0,
    cholesterol: 0,
    sodium: 420,
    potassium: 520,
    vitaminA: 80,
    vitaminC: 8,
    vitaminD: 0,
    vitaminE: 3.5,
    vitaminK: 35,
    thiamine: 0.35,
    riboflavin: 0.18,
    niacin: 2,
    pantothenicAcid: 1.2,
    vitaminB6: 0.5,
    biotin: 20,
    folate: 140,
    vitaminB12: 0,
    calcium: 120,
    iron: 3.5,
    magnesium: 85,
    phosphorus: 240,
    zinc: 2.8,
    copper: 0.5,
    manganese: 1,
    selenium: 5,
    imageUrl: '/images/hummus-pita.jpg',
  },
  {
    id: 'falafel',
    name: 'Falafel Wrap',
    category: 'arab',
    servingSize: 180,
    servingUnit: 'g',
    calories: 380,
    protein: 14,
    carbs: 42,
    fat: 18,
    fiber: 9,
    saturatedFat: 3,
    transFat: 0,
    cholesterol: 0,
    sodium: 580,
    potassium: 480,
    vitaminA: 120,
    vitaminC: 10,
    vitaminD: 0,
    vitaminE: 2.8,
    vitaminK: 40,
    thiamine: 0.3,
    riboflavin: 0.2,
    niacin: 2.5,
    pantothenicAcid: 1,
    vitaminB6: 0.4,
    biotin: 15,
    folate: 130,
    vitaminB12: 0,
    calcium: 140,
    iron: 3.2,
    magnesium: 70,
    phosphorus: 200,
    zinc: 2.5,
    copper: 0.4,
    manganese: 0.8,
    selenium: 8,
    imageUrl: '/images/falafel.jpg',
  },

  // BREAKFAST
  {
    id: 'eggs-breakfast',
    name: 'Eggs & Toast Breakfast',
    category: 'breakfast',
    servingSize: 220,
    servingUnit: 'g',
    calories: 420,
    protein: 18,
    carbs: 35,
    fat: 20,
    fiber: 3,
    saturatedFat: 8,
    transFat: 0.5,
    cholesterol: 372,
    sodium: 580,
    potassium: 280,
    vitaminA: 280,
    vitaminC: 2,
    vitaminD: 1.8,
    vitaminE: 2,
    vitaminK: 8,
    thiamine: 0.22,
    riboflavin: 0.35,
    niacin: 0.5,
    pantothenicAcid: 1.8,
    vitaminB6: 0.12,
    biotin: 25,
    folate: 45,
    vitaminB12: 0.8,
    calcium: 240,
    iron: 2.8,
    magnesium: 45,
    phosphorus: 280,
    zinc: 1.8,
    copper: 0.15,
    manganese: 0.4,
    selenium: 18,
    imageUrl: '/images/eggs-toast.jpg',
  },
  {
    id: 'oatmeal',
    name: 'Oatmeal with Berries',
    category: 'breakfast',
    servingSize: 250,
    servingUnit: 'g',
    calories: 280,
    protein: 8,
    carbs: 52,
    fat: 5,
    fiber: 8,
    saturatedFat: 1,
    transFat: 0,
    cholesterol: 2,
    sodium: 120,
    potassium: 380,
    vitaminA: 80,
    vitaminC: 18,
    vitaminD: 0,
    vitaminE: 2,
    vitaminK: 5,
    thiamine: 0.28,
    riboflavin: 0.12,
    niacin: 1.2,
    pantothenicAcid: 0.8,
    vitaminB6: 0.2,
    biotin: 12,
    folate: 35,
    vitaminB12: 0,
    calcium: 240,
    iron: 2.8,
    magnesium: 120,
    phosphorus: 240,
    zinc: 2,
    copper: 0.25,
    manganese: 2.2,
    selenium: 8,
    imageUrl: '/images/oatmeal.jpg',
  },
  {
    id: 'pancakes',
    name: 'Pancakes with Syrup',
    category: 'breakfast',
    servingSize: 240,
    servingUnit: 'g',
    calories: 480,
    protein: 10,
    carbs: 68,
    fat: 18,
    fiber: 1,
    saturatedFat: 5,
    transFat: 0.3,
    cholesterol: 140,
    sodium: 720,
    potassium: 200,
    vitaminA: 180,
    vitaminC: 1,
    vitaminD: 0.5,
    vitaminE: 1,
    vitaminK: 4,
    thiamine: 0.25,
    riboflavin: 0.28,
    niacin: 1.5,
    pantothenicAcid: 0.6,
    vitaminB6: 0.08,
    biotin: 8,
    folate: 30,
    vitaminB12: 0.2,
    calcium: 260,
    iron: 1.8,
    magnesium: 35,
    phosphorus: 200,
    zinc: 1,
    copper: 0.08,
    manganese: 0.3,
    selenium: 12,
    imageUrl: '/images/pancakes.jpg',
  },

  // DRINKS
  {
    id: 'coffee',
    name: 'Coffee with Milk',
    category: 'drinks',
    servingSize: 250,
    servingUnit: 'ml',
    calories: 80,
    protein: 3,
    carbs: 6,
    fat: 3,
    fiber: 0,
    saturatedFat: 2,
    transFat: 0,
    cholesterol: 10,
    sodium: 120,
    potassium: 150,
    vitaminA: 45,
    vitaminC: 0,
    vitaminD: 0.8,
    vitaminE: 0.2,
    vitaminK: 0.5,
    thiamine: 0.05,
    riboflavin: 0.15,
    niacin: 0.2,
    pantothenicAcid: 0.3,
    vitaminB6: 0.05,
    biotin: 2,
    folate: 5,
    vitaminB12: 0.2,
    calcium: 200,
    iron: 0.2,
    magnesium: 12,
    phosphorus: 150,
    zinc: 0.3,
    copper: 0.02,
    manganese: 0.05,
    selenium: 2,
    imageUrl: '/images/coffee.jpg',
  },
  {
    id: 'smoothie',
    name: 'Fruit Smoothie',
    category: 'drinks',
    servingSize: 300,
    servingUnit: 'ml',
    calories: 220,
    protein: 6,
    carbs: 42,
    fat: 2,
    fiber: 4,
    saturatedFat: 0.5,
    transFat: 0,
    cholesterol: 5,
    sodium: 80,
    potassium: 520,
    vitaminA: 280,
    vitaminC: 35,
    vitaminD: 0.5,
    vitaminE: 1.5,
    vitaminK: 8,
    thiamine: 0.12,
    riboflavin: 0.2,
    niacin: 0.8,
    pantothenicAcid: 0.5,
    vitaminB6: 0.3,
    biotin: 8,
    folate: 45,
    vitaminB12: 0.1,
    calcium: 180,
    iron: 0.8,
    magnesium: 45,
    phosphorus: 120,
    zinc: 0.5,
    copper: 0.15,
    manganese: 0.3,
    selenium: 5,
    imageUrl: '/images/smoothie.jpg',
  },
];
