export type FoodItem = {
  id: string;
  name: string;
  category: 'tunisian' | 'burger' | 'cake' | 'thai' | 'arab' | 'healthy' | 'vegetable' | 'fruit' | 'drink' | 'dairy' | 'grain' | 'meat' | 'seafood' | 'other';
  image: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber: number;
  servingSize: string;
  vitamins: Record<string, number>;
  minerals: Record<string, number>;
};


const baseVitamins = {
  'vitamin_a': 0,
  'vitamin_b1': 0,
  'vitamin_b2': 0,
  'vitamin_b3': 0,
  'vitamin_b5': 0,
  'vitamin_b6': 0,
  'vitamin_b7': 0,
  'vitamin_b9': 0,
  'vitamin_b12': 0,
  'vitamin_c': 0,
  'vitamin_d': 0,
  'vitamin_e': 0,
  'vitamin_k': 0,
};

const baseMinerals = {
  'calcium': 0,
  'iron': 0,
  'magnesium': 0,
  'phosphorus': 0,
  'potassium': 0,
  'zinc': 0,
  'copper': 0,
  'manganese': 0,
  'selenium': 0,
  'iodine': 0,
};

export const parseServingSize = (servingSize: string): number => {
  const numericValue = parseInt(servingSize.replace(/\D/g, ''));
  return isNaN(numericValue) || numericValue === 0 ? 100 : numericValue;
};

export const nutritionDatabase: FoodItem[] = [
  // TUNISIAN FOODS
  {
    id: 'tunisian_tajine_meat',
    name: 'Tajine à la Viande',
    category: 'tunisian',
    image: '/foods/tajine-meat.jpg',
    calories: 320,
    protein: 28,
    carbs: 18,
    fat: 16,
    fiber: 3,
    servingSize: '250g',
    vitamins: { ...baseVitamins, 'vitamin_a': 850, 'vitamin_c': 15, 'vitamin_b12': 1.2 },
    minerals: { ...baseMinerals, 'iron': 3.2, 'zinc': 4.1, 'potassium': 580 },
  },
  {
    id: 'tunisian_riz_djerbien',
    name: 'Riz Djerbien',
    category: 'tunisian',
    image: '/foods/riz-djerbien.jpg',
    calories: 380,
    protein: 22,
    carbs: 42,
    fat: 14,
    fiber: 2,
    servingSize: '280g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.35, 'vitamin_b3': 3.2, 'vitamin_b9': 45 },
    minerals: { ...baseMinerals, 'iron': 2.8, 'zinc': 3.5, 'magnesium': 95 },
  },
  {
    id: 'tunisian_osban',
    name: 'Osban',
    category: 'tunisian',
    image: '/foods/osban.jpg',
    calories: 410,
    protein: 18,
    carbs: 48,
    fat: 18,
    fiber: 4,
    servingSize: '220g',
    vitamins: { ...baseVitamins, 'vitamin_a': 720, 'vitamin_c': 8, 'vitamin_b6': 0.28 },
    minerals: { ...baseMinerals, 'iron': 2.5, 'calcium': 180, 'magnesium': 72 },
  },
  {
    id: 'tunisian_couscous_traditional',
    name: 'Couscous Traditionnel',
    category: 'tunisian',
    image: '/foods/couscous.jpg',
    calories: 350,
    protein: 16,
    carbs: 55,
    fat: 8,
    fiber: 3,
    servingSize: '250g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.42, 'vitamin_b2': 0.16, 'vitamin_b3': 4.5, 'vitamin_b9': 85 },
    minerals: { ...baseMinerals, 'iron': 3.1, 'magnesium': 108, 'zinc': 2.8 },
  },
  {
    id: 'tunisian_brik_egg',
    name: 'Brik à l\'Oeuf',
    category: 'tunisian',
    image: '/foods/brik-egg.jpg',
    calories: 280,
    protein: 14,
    carbs: 22,
    fat: 16,
    fiber: 1,
    servingSize: '140g',
    vitamins: { ...baseVitamins, 'vitamin_a': 540, 'vitamin_b12': 0.6, 'vitamin_d': 2.1 },
    minerals: { ...baseMinerals, 'iron': 1.8, 'calcium': 120, 'zinc': 1.5 },
  },
  {
    id: 'tunisian_chakchouka',
    name: 'Chakchouka',
    category: 'tunisian',
    image: '/foods/chakchouka.jpg',
    calories: 220,
    protein: 12,
    carbs: 16,
    fat: 12,
    fiber: 4,
    servingSize: '200g',
    vitamins: { ...baseVitamins, 'vitamin_a': 1260, 'vitamin_c': 35, 'vitamin_e': 2.8 },
    minerals: { ...baseMinerals, 'iron': 2.5, 'potassium': 650, 'magnesium': 52 },
  },
  {
    id: 'tunisian_shorba',
    name: 'Shorba (Soupe Traditionnelle)',
    category: 'tunisian',
    image: '/foods/shorba.jpg',
    calories: 180,
    protein: 14,
    carbs: 18,
    fat: 6,
    fiber: 2,
    servingSize: '300ml',
    vitamins: { ...baseVitamins, 'vitamin_a': 680, 'vitamin_c': 12, 'vitamin_b9': 35 },
    minerals: { ...baseMinerals, 'iron': 2.1, 'calcium': 95, 'potassium': 480 },
  },
  {
    id: 'tunisian_salata_mechwa',
    name: 'Salade Méchouia',
    category: 'tunisian',
    image: '/foods/salata-mechwa.jpg',
    calories: 140,
    protein: 6,
    carbs: 14,
    fat: 7,
    fiber: 3,
    servingSize: '200g',
    vitamins: { ...baseVitamins, 'vitamin_a': 1450, 'vitamin_c': 28, 'vitamin_e': 3.2 },
    minerals: { ...baseMinerals, 'potassium': 580, 'iron': 1.8, 'magnesium': 48 },
  },
  {
    id: 'tunisian_lablabi',
    name: 'Lablabi',
    category: 'tunisian',
    image: '/foods/lablabi.jpg',
    calories: 280,
    protein: 14,
    carbs: 38,
    fat: 6,
    fiber: 8,
    servingSize: '300g',
    vitamins: { ...baseVitamins, 'vitamin_a': 45, 'vitamin_c': 5, 'vitamin_b1': 0.32 },
    minerals: { ...baseMinerals, 'iron': 3.8, 'magnesium': 95, 'zinc': 2.4 },
  },
  {
    id: 'tunisian_merguez',
    name: 'Merguez',
    category: 'tunisian',
    image: '/foods/merguez.jpg',
    calories: 340,
    protein: 18,
    carbs: 2,
    fat: 28,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b12': 1.2, 'vitamin_b6': 0.35 },
    minerals: { ...baseMinerals, 'iron': 2.1, 'zinc': 4.5, 'potassium': 280 },
  },
  {
    id: 'tunisian_fricassee',
    name: 'Fricassée',
    category: 'tunisian',
    image: '/foods/fricassee.jpg',
    calories: 320,
    protein: 16,
    carbs: 28,
    fat: 18,
    fiber: 1,
    servingSize: '200g',
    vitamins: { ...baseVitamins, 'vitamin_a': 420, 'vitamin_b1': 0.25, 'vitamin_b12': 0.5 },
    minerals: { ...baseMinerals, 'iron': 1.9, 'calcium': 145, 'zinc': 2.2 },
  },
  {
    id: 'tunisian_kaak_warka',
    name: 'Kaak Warka',
    category: 'tunisian',
    image: '/foods/kaak-warka.jpg',
    calories: 380,
    protein: 8,
    carbs: 42,
    fat: 20,
    fiber: 2,
    servingSize: '120g',
    vitamins: { ...baseVitamins, 'vitamin_e': 2.1, 'vitamin_b1': 0.18 },
    minerals: { ...baseMinerals, 'magnesium': 42, 'phosphorus': 155 },
  },
  {
    id: 'tunisian_makroudh',
    name: 'Makroudh',
    category: 'tunisian',
    image: '/foods/makroudh.jpg',
    calories: 420,
    protein: 6,
    carbs: 52,
    fat: 22,
    fiber: 2,
    servingSize: '80g',
    vitamins: { ...baseVitamins, 'vitamin_e': 1.8, 'vitamin_b1': 0.12 },
    minerals: { ...baseMinerals, 'iron': 1.5, 'magnesium': 35, 'zinc': 0.8 },
  },
  {
    id: 'tunisian_mloukhia',
    name: 'Mloukhia',
    category: 'tunisian',
    image: '/foods/mloukhia.jpg',
    calories: 180,
    protein: 10,
    carbs: 20,
    fat: 7,
    fiber: 5,
    servingSize: '250g',
    vitamins: { ...baseVitamins, 'vitamin_a': 2840, 'vitamin_c': 18, 'vitamin_k': 210 },
    minerals: { ...baseMinerals, 'iron': 2.8, 'calcium': 165, 'magnesium': 78 },
  },
  {
    id: 'tunisian_chorba_frik',
    name: 'Chorba au Frik',
    category: 'tunisian',
    image: '/foods/chorba-frik.jpg',
    calories: 220,
    protein: 12,
    carbs: 28,
    fat: 6,
    fiber: 4,
    servingSize: '280g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.28, 'vitamin_b9': 42 },
    minerals: { ...baseMinerals, 'iron': 2.6, 'magnesium': 85, 'zinc': 2.3 },
  },
  // VEGETABLES
  {
    id: 'veg_tomato',
    name: 'Tomate',
    category: 'vegetable',
    image: '/foods/tomato.jpg',
    calories: 18,
    protein: 0.9,
    carbs: 3.9,
    fat: 0.2,
    fiber: 1.2,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 42, 'vitamin_c': 14, 'vitamin_k': 7.9, 'vitamin_b9': 15 },
    minerals: { ...baseMinerals, 'potassium': 237, 'magnesium': 11, 'iron': 0.3 },
  },
  {
    id: 'veg_carrot',
    name: 'Carotte',
    category: 'vegetable',
    image: '/foods/carrot.jpg',
    calories: 41,
    protein: 0.9,
    carbs: 10,
    fat: 0.2,
    fiber: 2.8,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 835, 'vitamin_c': 5.5, 'vitamin_k': 13.2, 'vitamin_b6': 0.14 },
    minerals: { ...baseMinerals, 'potassium': 320, 'magnesium': 12, 'iron': 0.3 },
  },
  {
    id: 'veg_lettuce',
    name: 'Laitue',
    category: 'vegetable',
    image: '/foods/lettuce.jpg',
    calories: 15,
    protein: 1.4,
    carbs: 2.9,
    fat: 0.2,
    fiber: 1.3,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 166, 'vitamin_c': 3.7, 'vitamin_k': 102, 'vitamin_b9': 38 },
    minerals: { ...baseMinerals, 'potassium': 194, 'calcium': 35, 'magnesium': 13 },
  },
  {
    id: 'veg_spinach',
    name: 'Épinards',
    category: 'vegetable',
    image: '/foods/spinach.jpg',
    calories: 23,
    protein: 2.7,
    carbs: 3.6,
    fat: 0.4,
    fiber: 2.2,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 469, 'vitamin_c': 8.4, 'vitamin_k': 483, 'vitamin_b9': 194 },
    minerals: { ...baseMinerals, 'iron': 2.7, 'magnesium': 79, 'calcium': 99, 'potassium': 558 },
  },
  {
    id: 'veg_broccoli',
    name: 'Brocoli',
    category: 'vegetable',
    image: '/foods/broccoli.jpg',
    calories: 34,
    protein: 2.8,
    carbs: 7,
    fat: 0.4,
    fiber: 2.4,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 623, 'vitamin_c': 89.2, 'vitamin_k': 102, 'vitamin_b9': 63 },
    minerals: { ...baseMinerals, 'calcium': 47, 'iron': 0.7, 'magnesium': 21, 'potassium': 316 },
  },
  {
    id: 'veg_onion',
    name: 'Oignon',
    category: 'vegetable',
    image: '/foods/onion.jpg',
    calories: 40,
    protein: 1.1,
    carbs: 9,
    fat: 0.1,
    fiber: 1.7,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_c': 7.4, 'vitamin_b6': 0.12, 'vitamin_b9': 19 },
    minerals: { ...baseMinerals, 'potassium': 146, 'magnesium': 10, 'calcium': 23 },
  },
  {
    id: 'veg_pepper',
    name: 'Poivron',
    category: 'vegetable',
    image: '/foods/pepper.jpg',
    calories: 31,
    protein: 1,
    carbs: 6,
    fat: 0.3,
    fiber: 2,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 318, 'vitamin_c': 80.4, 'vitamin_k': 4.8, 'vitamin_b6': 0.29 },
    minerals: { ...baseMinerals, 'potassium': 175, 'magnesium': 12, 'calcium': 12 },
  },
  {
    id: 'veg_cucumber',
    name: 'Concombre',
    category: 'vegetable',
    image: '/foods/cucumber.jpg',
    calories: 16,
    protein: 0.7,
    carbs: 3.6,
    fat: 0.1,
    fiber: 0.5,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 105, 'vitamin_c': 2.8, 'vitamin_k': 16.4, 'vitamin_b9': 7 },
    minerals: { ...baseMinerals, 'potassium': 147, 'magnesium': 13, 'calcium': 16 },
  },
  {
    id: 'veg_zucchini',
    name: 'Courgette',
    category: 'vegetable',
    image: '/foods/zucchini.jpg',
    calories: 21,
    protein: 1.4,
    carbs: 3.5,
    fat: 0.4,
    fiber: 1,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 393, 'vitamin_c': 20, 'vitamin_k': 4.3, 'vitamin_b6': 0.15 },
    minerals: { ...baseMinerals, 'potassium': 261, 'magnesium': 18, 'calcium': 18 },
  },
  {
    id: 'veg_eggplant',
    name: 'Aubergine',
    category: 'vegetable',
    image: '/foods/eggplant.jpg',
    calories: 25,
    protein: 0.98,
    carbs: 5.9,
    fat: 0.2,
    fiber: 3,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 23, 'vitamin_c': 3.5, 'vitamin_k': 3.5, 'vitamin_b6': 0.08 },
    minerals: { ...baseMinerals, 'potassium': 229, 'magnesium': 14, 'calcium': 9, 'iron': 0.2 },
  },
  {
    id: 'veg_cauliflower',
    name: 'Chou-fleur',
    category: 'vegetable',
    image: '/foods/cauliflower.jpg',
    calories: 25,
    protein: 1.9,
    carbs: 5,
    fat: 0.3,
    fiber: 2.4,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 22, 'vitamin_c': 46.4, 'vitamin_k': 20.3, 'vitamin_b9': 57 },
    minerals: { ...baseMinerals, 'potassium': 299, 'magnesium': 15, 'calcium': 22 },
  },
  // FRUITS
  {
    id: 'fruit_apple',
    name: 'Pomme',
    category: 'fruit',
    image: '/foods/apple.jpg',
    calories: 52,
    protein: 0.3,
    carbs: 14,
    fat: 0.2,
    fiber: 2.4,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 3, 'vitamin_c': 5.7, 'vitamin_k': 2.2, 'vitamin_b6': 0.04 },
    minerals: { ...baseMinerals, 'potassium': 107, 'magnesium': 5, 'calcium': 6 },
  },
  {
    id: 'fruit_banana',
    name: 'Banane',
    category: 'fruit',
    image: '/foods/banana.jpg',
    calories: 89,
    protein: 1.1,
    carbs: 23,
    fat: 0.3,
    fiber: 2.6,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 3, 'vitamin_c': 8.7, 'vitamin_b6': 0.4, 'vitamin_b9': 25 },
    minerals: { ...baseMinerals, 'potassium': 358, 'magnesium': 27, 'calcium': 5 },
  },
  {
    id: 'fruit_orange',
    name: 'Orange',
    category: 'fruit',
    image: '/foods/orange.jpg',
    calories: 47,
    protein: 0.9,
    carbs: 12,
    fat: 0.1,
    fiber: 2.4,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 11, 'vitamin_c': 53.2, 'vitamin_b9': 30, 'vitamin_b1': 0.09 },
    minerals: { ...baseMinerals, 'potassium': 181, 'magnesium': 10, 'calcium': 40 },
  },
  {
    id: 'fruit_strawberry',
    name: 'Fraise',
    category: 'fruit',
    image: '/foods/strawberry.jpg',
    calories: 32,
    protein: 0.8,
    carbs: 8,
    fat: 0.3,
    fiber: 2,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 12, 'vitamin_c': 58.8, 'vitamin_k': 2.2, 'vitamin_b9': 24 },
    minerals: { ...baseMinerals, 'potassium': 153, 'magnesium': 13, 'calcium': 16 },
  },
  {
    id: 'fruit_blueberry',
    name: 'Myrtille',
    category: 'fruit',
    image: '/foods/blueberry.jpg',
    calories: 57,
    protein: 0.7,
    carbs: 14,
    fat: 0.3,
    fiber: 2.4,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 38, 'vitamin_c': 9.7, 'vitamin_k': 19.3, 'vitamin_b6': 0.07 },
    minerals: { ...baseMinerals, 'potassium': 147, 'magnesium': 9, 'calcium': 6 },
  },
  {
    id: 'fruit_grape',
    name: 'Raisin',
    category: 'fruit',
    image: '/foods/grape.jpg',
    calories: 67,
    protein: 0.7,
    carbs: 17,
    fat: 0.4,
    fiber: 0.9,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 3, 'vitamin_c': 3.2, 'vitamin_k': 14.6, 'vitamin_b6': 0.09 },
    minerals: { ...baseMinerals, 'potassium': 191, 'magnesium': 7, 'calcium': 10 },
  },
  {
    id: 'fruit_watermelon',
    name: 'Pastèque',
    category: 'fruit',
    image: '/foods/watermelon.jpg',
    calories: 30,
    protein: 0.6,
    carbs: 8,
    fat: 0.2,
    fiber: 0.4,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 28, 'vitamin_c': 8.1, 'vitamin_b6': 0.05, 'vitamin_b9': 3 },
    minerals: { ...baseMinerals, 'potassium': 112, 'magnesium': 10, 'calcium': 7 },
  },
  {
    id: 'fruit_mango',
    name: 'Mangue',
    category: 'fruit',
    image: '/foods/mango.jpg',
    calories: 60,
    protein: 0.8,
    carbs: 15,
    fat: 0.4,
    fiber: 1.6,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 54, 'vitamin_c': 36.5, 'vitamin_k': 4.2, 'vitamin_b6': 0.12 },
    minerals: { ...baseMinerals, 'potassium': 168, 'magnesium': 10, 'calcium': 11 },
  },
  {
    id: 'fruit_pineapple',
    name: 'Ananas',
    category: 'fruit',
    image: '/foods/pineapple.jpg',
    calories: 50,
    protein: 0.5,
    carbs: 13,
    fat: 0.1,
    fiber: 1.4,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 3, 'vitamin_c': 47.8, 'vitamin_b6': 0.11, 'vitamin_b9': 18 },
    minerals: { ...baseMinerals, 'potassium': 109, 'magnesium': 12, 'calcium': 13 },
  },
  {
    id: 'fruit_avocado',
    name: 'Avocat',
    category: 'fruit',
    image: '/foods/avocado.jpg',
    calories: 160,
    protein: 2,
    carbs: 9,
    fat: 15,
    fiber: 7,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 7, 'vitamin_c': 10, 'vitamin_k': 21, 'vitamin_e': 2.1, 'vitamin_b6': 0.26, 'vitamin_b9': 81 },
    minerals: { ...baseMinerals, 'potassium': 485, 'magnesium': 29, 'calcium': 12 },
  },
  // PROTEINS
  {
    id: 'meat_chicken_breast',
    name: 'Poitrine de Poulet',
    category: 'meat',
    image: '/foods/chicken-breast.jpg',
    calories: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b3': 9.2, 'vitamin_b6': 0.88, 'vitamin_b12': 0.3 },
    minerals: { ...baseMinerals, 'phosphorus': 220, 'selenium': 27, 'zinc': 0.7 },
  },
  {
    id: 'meat_beef',
    name: 'Boeuf',
    category: 'meat',
    image: '/foods/beef.jpg',
    calories: 250,
    protein: 26,
    carbs: 0,
    fat: 15,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b3': 5.5, 'vitamin_b6': 0.51, 'vitamin_b12': 2.4 },
    minerals: { ...baseMinerals, 'iron': 2.6, 'zinc': 6.3, 'phosphorus': 195 },
  },
  {
    id: 'meat_pork',
    name: 'Porc',
    category: 'meat',
    image: '/foods/pork.jpg',
    calories: 242,
    protein: 27,
    carbs: 0,
    fat: 14,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.54, 'vitamin_b3': 4.8, 'vitamin_b12': 0.7 },
    minerals: { ...baseMinerals, 'phosphorus': 220, 'selenium': 36, 'zinc': 2.7 },
  },
  {
    id: 'meat_turkey',
    name: 'Dinde',
    category: 'meat',
    image: '/foods/turkey.jpg',
    calories: 189,
    protein: 29,
    carbs: 0,
    fat: 7.4,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b3': 5.1, 'vitamin_b6': 0.57, 'vitamin_b12': 0.3 },
    minerals: { ...baseMinerals, 'selenium': 32, 'zinc': 1.6, 'phosphorus': 190 },
  },
  {
    id: 'seafood_salmon',
    name: 'Saumon',
    category: 'seafood',
    image: '/foods/salmon.jpg',
    calories: 206,
    protein: 22,
    carbs: 0,
    fat: 13,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 30, 'vitamin_d': 12.5, 'vitamin_b12': 3.2, 'vitamin_b3': 5.8 },
    minerals: { ...baseMinerals, 'selenium': 36, 'phosphorus': 240, 'potassium': 363 },
  },
  {
    id: 'seafood_tuna',
    name: 'Thon',
    category: 'seafood',
    image: '/foods/tuna.jpg',
    calories: 129,
    protein: 26,
    carbs: 0,
    fat: 1.3,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b3': 8.8, 'vitamin_b12': 2.4, 'vitamin_d': 4.1 },
    minerals: { ...baseMinerals, 'selenium': 90, 'phosphorus': 240, 'potassium': 279 },
  },
  {
    id: 'seafood_cod',
    name: 'Morue',
    category: 'seafood',
    image: '/foods/cod.jpg',
    calories: 82,
    protein: 18,
    carbs: 0,
    fat: 0.7,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_d': 10.3, 'vitamin_b12': 1.0 },
    minerals: { ...baseMinerals, 'selenium': 33, 'phosphorus': 200, 'potassium': 413 },
  },
  {
    id: 'seafood_shrimp',
    name: 'Crevettes',
    category: 'seafood',
    image: '/foods/shrimp.jpg',
    calories: 99,
    protein: 24,
    carbs: 0.2,
    fat: 0.3,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_d': 1.5, 'vitamin_b12': 0.8 },
    minerals: { ...baseMinerals, 'selenium': 38, 'iron': 0.5, 'zinc': 1.5 },
  },
  {
    id: 'dairy_milk',
    name: 'Lait',
    category: 'dairy',
    image: '/foods/milk.jpg',
    calories: 61,
    protein: 3.2,
    carbs: 4.8,
    fat: 3.3,
    fiber: 0,
    servingSize: '100ml',
    vitamins: { ...baseVitamins, 'vitamin_a': 28, 'vitamin_d': 1.3, 'vitamin_b12': 0.4, 'vitamin_b2': 0.14 },
    minerals: { ...baseMinerals, 'calcium': 113, 'phosphorus': 84, 'potassium': 132 },
  },
  {
    id: 'dairy_yogurt',
    name: 'Yaourt',
    category: 'dairy',
    image: '/foods/yogurt.jpg',
    calories: 59,
    protein: 3.5,
    carbs: 4.7,
    fat: 0.4,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 5, 'vitamin_d': 0.1, 'vitamin_b12': 0.2, 'vitamin_b2': 0.11 },
    minerals: { ...baseMinerals, 'calcium': 110, 'phosphorus': 95, 'potassium': 155 },
  },
  {
    id: 'dairy_cheese',
    name: 'Fromage',
    category: 'dairy',
    image: '/foods/cheese.jpg',
    calories: 402,
    protein: 25,
    carbs: 1.3,
    fat: 33,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 240, 'vitamin_d': 0.7, 'vitamin_b12': 0.7, 'vitamin_b2': 0.37 },
    minerals: { ...baseMinerals, 'calcium': 721, 'phosphorus': 515, 'zinc': 3.9 },
  },
  {
    id: 'egg_whole',
    name: 'Oeuf',
    category: 'meat',
    image: '/foods/egg.jpg',
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fat: 11,
    fiber: 0,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_a': 140, 'vitamin_d': 7.0, 'vitamin_b12': 1.1, 'vitamin_b7': 10 },
    minerals: { ...baseMinerals, 'phosphorus': 198, 'selenium': 32, 'zinc': 1.0 },
  },
  // GRAINS
  {
    id: 'grain_bread',
    name: 'Pain Blanc',
    category: 'grain',
    image: '/foods/bread.jpg',
    calories: 265,
    protein: 9,
    carbs: 49,
    fat: 3.3,
    fiber: 2.7,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.28, 'vitamin_b3': 2.8, 'vitamin_b9': 32 },
    minerals: { ...baseMinerals, 'iron': 1.8, 'magnesium': 23, 'zinc': 0.5 },
  },
  {
    id: 'grain_rice',
    name: 'Riz Blanc',
    category: 'grain',
    image: '/foods/rice.jpg',
    calories: 130,
    protein: 2.7,
    carbs: 28,
    fat: 0.3,
    fiber: 0.4,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.07, 'vitamin_b3': 1.5, 'vitamin_b9': 8 },
    minerals: { ...baseMinerals, 'iron': 0.2, 'magnesium': 12, 'manganese': 0.8 },
  },
  {
    id: 'grain_pasta',
    name: 'Pâtes',
    category: 'grain',
    image: '/foods/pasta.jpg',
    calories: 131,
    protein: 5,
    carbs: 25,
    fat: 1.1,
    fiber: 1.8,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.09, 'vitamin_b3': 1.8, 'vitamin_b9': 12 },
    minerals: { ...baseMinerals, 'iron': 1.8, 'magnesium': 16, 'zinc': 0.4 },
  },
  {
    id: 'grain_oats',
    name: 'Flocons d\'Avoine',
    category: 'grain',
    image: '/foods/oats.jpg',
    calories: 389,
    protein: 17,
    carbs: 66,
    fat: 7,
    fiber: 10,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.76, 'vitamin_b5': 1.35, 'vitamin_b9': 56 },
    minerals: { ...baseMinerals, 'iron': 4.3, 'magnesium': 177, 'zinc': 4.0 },
  },
  {
    id: 'grain_quinoa',
    name: 'Quinoa',
    category: 'grain',
    image: '/foods/quinoa.jpg',
    calories: 368,
    protein: 14,
    carbs: 64,
    fat: 6,
    fiber: 7,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.36, 'vitamin_b2': 0.32, 'vitamin_b9': 78 },
    minerals: { ...baseMinerals, 'iron': 8.0, 'magnesium': 197, 'zinc': 3.1 },
  },
  // DRINKS
  {
    id: 'drink_water',
    name: 'Eau',
    category: 'drink',
    image: '/foods/water.jpg',
    calories: 0,
    protein: 0,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: '250ml',
    vitamins: baseVitamins,
    minerals: baseMinerals,
  },
  {
    id: 'drink_coffee',
    name: 'Café',
    category: 'drink',
    image: '/foods/coffee.jpg',
    calories: 2,
    protein: 0.1,
    carbs: 0,
    fat: 0,
    fiber: 0,
    servingSize: '240ml',
    vitamins: baseVitamins,
    minerals: { ...baseMinerals, 'magnesium': 10, 'potassium': 96 },
  },
  {
    id: 'drink_tea',
    name: 'Thé',
    category: 'drink',
    image: '/foods/tea.jpg',
    calories: 1,
    protein: 0,
    carbs: 0.3,
    fat: 0,
    fiber: 0,
    servingSize: '240ml',
    vitamins: baseVitamins,
    minerals: { ...baseMinerals, 'potassium': 66, 'magnesium': 2 },
  },
  {
    id: 'drink_juice_orange',
    name: 'Jus d\'Orange',
    category: 'drink',
    image: '/foods/juice.jpg',
    calories: 45,
    protein: 0.7,
    carbs: 11,
    fat: 0.3,
    fiber: 0.2,
    servingSize: '240ml',
    vitamins: { ...baseVitamins, 'vitamin_a': 5, 'vitamin_c': 34, 'vitamin_b9': 9 },
    minerals: { ...baseMinerals, 'potassium': 237, 'calcium': 27, 'magnesium': 12 },
  },
  {
    id: 'drink_smoothie',
    name: 'Smoothie aux Fruits',
    category: 'drink',
    image: '/foods/smoothie.jpg',
    calories: 110,
    protein: 2,
    carbs: 24,
    fat: 1,
    fiber: 2,
    servingSize: '250ml',
    vitamins: { ...baseVitamins, 'vitamin_a': 45, 'vitamin_c': 35, 'vitamin_b6': 0.15, 'vitamin_b9': 25 },
    minerals: { ...baseMinerals, 'potassium': 350, 'magnesium': 25, 'calcium': 80 },
  },
  // ADDITIONAL ITEMS FOR VARIETY
  {
    id: 'nut_almond',
    name: 'Amandes',
    category: 'healthy',
    image: '/foods/almonds.jpg',
    calories: 579,
    protein: 21,
    carbs: 22,
    fat: 50,
    fiber: 13,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_e': 25.6, 'vitamin_b2': 1.14, 'vitamin_b9': 44 },
    minerals: { ...baseMinerals, 'magnesium': 270, 'calcium': 264, 'zinc': 3.1, 'iron': 3.7 },
  },
  {
    id: 'nut_walnut',
    name: 'Noix',
    category: 'healthy',
    image: '/foods/walnut.jpg',
    calories: 654,
    protein: 9,
    carbs: 14,
    fat: 65,
    fiber: 7,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_e': 1.6, 'vitamin_b1': 0.34, 'vitamin_b9': 98 },
    minerals: { ...baseMinerals, 'magnesium': 158, 'phosphorus': 346, 'copper': 1.59 },
  },
  {
    id: 'legume_lentil',
    name: 'Lentilles',
    category: 'healthy',
    image: '/foods/lentil.jpg',
    calories: 116,
    protein: 9,
    carbs: 20,
    fat: 0.4,
    fiber: 8,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.27, 'vitamin_b9': 181, 'vitamin_b6': 0.21 },
    minerals: { ...baseMinerals, 'iron': 3.3, 'magnesium': 36, 'zinc': 1.27 },
  },
  {
    id: 'legume_chickpea',
    name: 'Pois Chiches',
    category: 'healthy',
    image: '/foods/chickpea.jpg',
    calories: 164,
    protein: 9,
    carbs: 27,
    fat: 3,
    fiber: 7,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.12, 'vitamin_b9': 172, 'vitamin_b6': 0.14 },
    minerals: { ...baseMinerals, 'iron': 2.9, 'magnesium': 48, 'zinc': 1.53 },
  },
  {
    id: 'legume_bean',
    name: 'Haricots Noirs',
    category: 'healthy',
    image: '/foods/bean.jpg',
    calories: 132,
    protein: 9,
    carbs: 24,
    fat: 0.5,
    fiber: 6,
    servingSize: '100g',
    vitamins: { ...baseVitamins, 'vitamin_b1': 0.16, 'vitamin_b9': 149, 'vitamin_b6': 0.12 },
    minerals: { ...baseMinerals, 'iron': 2.1, 'magnesium': 70, 'zinc': 0.84 },
  },
];
